#!/usr/bin/env bash

# Update and install Nginx
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

# Start Nginx and allow HTTP traffic
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Set permissions and create backup of default index file
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Replace default index file with "Hello World!" message
echo -e "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx service
sudo service nginx restart

