#!/usr/bin/env bash
# Lists all the process in the system

echo "PID USER     %CPU %MEM COMMAND"
ps axo pid,user,%cpu,%mem,command --forest | awk '{printf "%-5s %-8s %-5s %-5s %s\n", $1, $2, $3, $4, $5}' | less
