#!/usr/bin/env bash
# fizzbuzz
for i in {1..100}; do 
    if ! ((i % 3)); then
        echo -n Fizz
    fi
    if ! ((i % 5)); then
        echo -n Buzz
    fi
    if ((i % 3)) && ((i % 5)); then
        echo -n $i
    fi
    echo
done
